/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tututugas;

/**
 *
 * @author Jaw
 */
import javax.swing.JOptionPane;
public class Kalkulautoor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Kalkulautoor.class.getName());

    /**
     * Creates new form Kalkulautoor
     */
    private double bilangan1 = 0;
    private String operator = "";
    private boolean siapInputBaru = true;

    public Kalkulautoor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private void tambahAngka(String angka) {
        if (siapInputBaru) {
            AngkaTF.setText(angka);
            siapInputBaru = false;
        } else {
            AngkaTF.setText(AngkaTF.getText() + angka);
        }
    }
    
    private void pilihOperator(String op) {
        if (!AngkaTF.getText().isEmpty()) {
            bilangan1 = Double.parseDouble(AngkaTF.getText());
            operator = op;
            siapInputBaru = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        AngkaTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        EmpatBT = new javax.swing.JButton();
        TujuhBT = new javax.swing.JButton();
        DelapanBT = new javax.swing.JButton();
        LimaBT = new javax.swing.JButton();
        SatuBT = new javax.swing.JButton();
        DuaBT = new javax.swing.JButton();
        SembilanBT = new javax.swing.JButton();
        EnamBT = new javax.swing.JButton();
        TigaBT = new javax.swing.JButton();
        KomaBT = new javax.swing.JButton();
        NolBT = new javax.swing.JButton();
        ClearBT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        SamadenganBT = new javax.swing.JButton();
        KaliBT = new javax.swing.JButton();
        TambahBT = new javax.swing.JButton();
        KurangBT = new javax.swing.JButton();
        BagiBT = new javax.swing.JButton();
        ModuloBT = new javax.swing.JButton();
        ExitBT = new javax.swing.JButton();
        BackspaceBT = new javax.swing.JButton();

        jButton8.setText("jButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        AngkaTF.setBackground(new java.awt.Color(255, 255, 255));
        AngkaTF.addActionListener(this::AngkaTFActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AngkaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(AngkaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        EmpatBT.setText("4");
        EmpatBT.addActionListener(this::EmpatBTActionPerformed);

        TujuhBT.setText("7");
        TujuhBT.addActionListener(this::TujuhBTActionPerformed);

        DelapanBT.setText("8");
        DelapanBT.addActionListener(this::DelapanBTActionPerformed);

        LimaBT.setText("5");
        LimaBT.addActionListener(this::LimaBTActionPerformed);

        SatuBT.setText("1");
        SatuBT.addActionListener(this::SatuBTActionPerformed);

        DuaBT.setText("2");
        DuaBT.addActionListener(this::DuaBTActionPerformed);

        SembilanBT.setText("9");
        SembilanBT.addActionListener(this::SembilanBTActionPerformed);

        EnamBT.setText("6");
        EnamBT.addActionListener(this::EnamBTActionPerformed);

        TigaBT.setText("3");
        TigaBT.addActionListener(this::TigaBTActionPerformed);

        KomaBT.setText(".");
        KomaBT.addActionListener(this::KomaBTActionPerformed);

        NolBT.setText("0");
        NolBT.addActionListener(this::NolBTActionPerformed);

        ClearBT.setText("C");
        ClearBT.addActionListener(this::ClearBTActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TujuhBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpatBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SatuBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KomaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DelapanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(NolBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(DuaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(LimaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(ClearBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EnamBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TigaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SembilanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DelapanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SembilanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TujuhBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpatBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnamBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SatuBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DuaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TigaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NolBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KomaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        SamadenganBT.setText("=");
        SamadenganBT.addActionListener(this::SamadenganBTActionPerformed);

        KaliBT.setText("*");
        KaliBT.addActionListener(this::KaliBTActionPerformed);

        TambahBT.setText("+");
        TambahBT.addActionListener(this::TambahBTActionPerformed);

        KurangBT.setText("-");
        KurangBT.addActionListener(this::KurangBTActionPerformed);

        BagiBT.setText("/");
        BagiBT.addActionListener(this::BagiBTActionPerformed);

        ModuloBT.setText("%");
        ModuloBT.addActionListener(this::ModuloBTActionPerformed);

        ExitBT.setText("E");
        ExitBT.addActionListener(this::ExitBTActionPerformed);

        BackspaceBT.setText("B");
        BackspaceBT.addActionListener(this::BackspaceBTActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SamadenganBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(TambahBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KaliBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackspaceBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ModuloBT, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(BagiBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KurangBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KurangBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TambahBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BagiBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KaliBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SamadenganBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModuloBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackspaceBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AngkaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AngkaTFActionPerformed

    private void ExitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTActionPerformed
       int reply = JOptionPane.showConfirmDialog(null, "Yakin ingin keluar?",
                    "Konfirmasi keluar aplikasi",
                    JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_ExitBTActionPerformed

    private void BackspaceBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackspaceBTActionPerformed
        String currentText = AngkaTF.getText();
        if (currentText.length() > 0) {
            AngkaTF.setText(currentText.substring(0, currentText.length() - 1));
        }
    }//GEN-LAST:event_BackspaceBTActionPerformed

    private void ClearBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTActionPerformed
        AngkaTF.setText("");
        bilangan1 = 0;
        operator = "";
        siapInputBaru = true;
    }//GEN-LAST:event_ClearBTActionPerformed

    private void NolBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NolBTActionPerformed
        tambahAngka("0");
    }//GEN-LAST:event_NolBTActionPerformed

    private void SatuBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatuBTActionPerformed
        tambahAngka("1");
    }//GEN-LAST:event_SatuBTActionPerformed

    private void DuaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuaBTActionPerformed
        tambahAngka("2");
    }//GEN-LAST:event_DuaBTActionPerformed

    private void TigaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TigaBTActionPerformed
        tambahAngka("3");
    }//GEN-LAST:event_TigaBTActionPerformed

    private void EmpatBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpatBTActionPerformed
        tambahAngka("4");
    }//GEN-LAST:event_EmpatBTActionPerformed

    private void LimaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimaBTActionPerformed
        tambahAngka("5");
    }//GEN-LAST:event_LimaBTActionPerformed

    private void EnamBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnamBTActionPerformed
        tambahAngka("6");
    }//GEN-LAST:event_EnamBTActionPerformed

    private void TujuhBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuhBTActionPerformed
        tambahAngka("7");
    }//GEN-LAST:event_TujuhBTActionPerformed

    private void DelapanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelapanBTActionPerformed
        tambahAngka("8");
    }//GEN-LAST:event_DelapanBTActionPerformed

    private void SembilanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SembilanBTActionPerformed
        tambahAngka("9");
    }//GEN-LAST:event_SembilanBTActionPerformed

    private void KomaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KomaBTActionPerformed
        if (!AngkaTF.getText().contains(".")) {
            tambahAngka(".");
        }
    }//GEN-LAST:event_KomaBTActionPerformed

    private void ModuloBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModuloBTActionPerformed
        pilihOperator("%");
    }//GEN-LAST:event_ModuloBTActionPerformed

    private void SamadenganBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamadenganBTActionPerformed
       if (!operator.isEmpty() && !AngkaTF.getText().isEmpty()) {
            double bilangan2 = Double.parseDouble(AngkaTF.getText());
            double hasil = 0;
            
            switch (operator) {
                case "+": hasil = bilangan1 + bilangan2; break;
                case "-": hasil = bilangan1 - bilangan2; break;
                case "*": hasil = bilangan1 * bilangan2; break;
                case "/": hasil = (bilangan2 != 0) ? (bilangan1 / bilangan2) : 0; break;
                case "%": hasil = bilangan1 % bilangan2; break;
            }
            
            if (hasil % 1 == 0) {
                AngkaTF.setText(String.valueOf((int) hasil));
            } else {
                AngkaTF.setText(String.valueOf(hasil));
            }
            operator = "";
            siapInputBaru = true;
        }
    }//GEN-LAST:event_SamadenganBTActionPerformed

    private void BagiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagiBTActionPerformed
        pilihOperator("/");
    }//GEN-LAST:event_BagiBTActionPerformed

    private void KaliBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaliBTActionPerformed
        pilihOperator("*");
    }//GEN-LAST:event_KaliBTActionPerformed

    private void KurangBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KurangBTActionPerformed
        pilihOperator("-");
    }//GEN-LAST:event_KurangBTActionPerformed

    private void TambahBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahBTActionPerformed
        pilihOperator("+");
    }//GEN-LAST:event_TambahBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting AngkaTFnal) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Kalkulautoor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AngkaTF;
    private javax.swing.JButton BackspaceBT;
    private javax.swing.JButton BagiBT;
    private javax.swing.JButton ClearBT;
    private javax.swing.JButton DelapanBT;
    private javax.swing.JButton DuaBT;
    private javax.swing.JButton EmpatBT;
    private javax.swing.JButton EnamBT;
    private javax.swing.JButton ExitBT;
    private javax.swing.JButton KaliBT;
    private javax.swing.JButton KomaBT;
    private javax.swing.JButton KurangBT;
    private javax.swing.JButton LimaBT;
    private javax.swing.JButton ModuloBT;
    private javax.swing.JButton NolBT;
    private javax.swing.JButton SamadenganBT;
    private javax.swing.JButton SatuBT;
    private javax.swing.JButton SembilanBT;
    private javax.swing.JButton TambahBT;
    private javax.swing.JButton TigaBT;
    private javax.swing.JButton TujuhBT;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
