/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tututugas;

/**
 *
 * @author Jaw
 */

import javax.swing.*;
import java.io.FileWriter;
import java.io.IOException;

public class PenentuJumlahHari extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PenentuJumlahHari.class.getName());

    /**
     * Creates new form PenentuJumlahHari
     */
    public PenentuJumlahHari() {
        initComponents();
        BulanCombo.removeAllItems();
        BulanCombo.addItem("Januari");
        BulanCombo.addItem("Februari");
        BulanCombo.addItem("Maret");
        BulanCombo.addItem("April");
        BulanCombo.addItem("Mei");
        BulanCombo.addItem("Juni");
        BulanCombo.addItem("Juli");
        BulanCombo.addItem("Agustus");
        BulanCombo.addItem("September");
        BulanCombo.addItem("Oktober");
        BulanCombo.addItem("November");
        BulanCombo.addItem("Desember");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TahunTF = new javax.swing.JTextField();
        BulanCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        HasilLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        HitungBT = new javax.swing.JButton();
        HapusBT = new javax.swing.JButton();
        SimpanBT = new javax.swing.JButton();
        KeluarBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tahun");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bulan");

        TahunTF.setBackground(new java.awt.Color(255, 255, 255));
        TahunTF.setForeground(new java.awt.Color(0, 0, 0));
        TahunTF.addActionListener(this::TahunTFActionPerformed);

        BulanCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BulanCombo.addActionListener(this::BulanComboActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TahunTF)
                    .addComponent(BulanCombo, 0, 119, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TahunTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BulanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        HasilLabel.setForeground(new java.awt.Color(0, 0, 0));
        HasilLabel.setText("Hasil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(HasilLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(HasilLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        HitungBT.setText("Hitung");
        HitungBT.addActionListener(this::HitungBTActionPerformed);

        HapusBT.setText("Hapus");
        HapusBT.addActionListener(this::HapusBTActionPerformed);

        SimpanBT.setText("Simpan");
        SimpanBT.addActionListener(this::SimpanBTActionPerformed);

        KeluarBT.setText("Keluar");
        KeluarBT.addActionListener(this::KeluarBTActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(HitungBT)
                .addGap(30, 30, 30)
                .addComponent(HapusBT)
                .addGap(35, 35, 35)
                .addComponent(SimpanBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(KeluarBT)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HitungBT)
                    .addComponent(HapusBT)
                    .addComponent(SimpanBT)
                    .addComponent(KeluarBT))
                .addGap(19, 19, 19))
        );

        jLabel1.setText("Aplikasi Penentu Jumlah Hari");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TahunTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunTFActionPerformed
        HitungBTActionPerformed(evt);
    }//GEN-LAST:event_TahunTFActionPerformed

    private void BulanComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BulanComboActionPerformed

    private void HitungBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungBTActionPerformed
        try {
            String tahunStr = TahunTF.getText().trim();
            if (tahunStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tahun tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int tahun = Integer.parseInt(tahunStr);
            String bulan = (String) BulanCombo.getSelectedItem();
            
            // Memanggil class HitungHari terpisah
            HitungHari kalkulator = new HitungHari();
            int jumlahHari = kalkulator.hitung(tahun, bulan);
            
            HasilLabel.setText("Jumlah hari pada bulan " + bulan + " tahun " + tahun + " adalah " + jumlahHari);
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Input tahun harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_HitungBTActionPerformed

    private void HapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusBTActionPerformed
        TahunTF.setText("");
        BulanCombo.setSelectedIndex(0);
        HasilLabel.setText("Hasil");
        TahunTF.requestFocus();
    }//GEN-LAST:event_HapusBTActionPerformed

    private void SimpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanBTActionPerformed
        String teksHasil = HasilLabel.getText();
        
        if (teksHasil.equals("Hasil") || teksHasil.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Belum ada hasil perhitungan untuk disimpan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try (FileWriter writer = new FileWriter("hasil_perhitungan.txt", true)) {
            writer.write(teksHasil + "\n");
            JOptionPane.showMessageDialog(this, "Hasil berhasil disimpan ke 'hasil_perhitungan.txt'!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan file!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SimpanBTActionPerformed

    private void KeluarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarBTActionPerformed
        int reply = JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?",
                    "Konfirmasi Keluar",
                    JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_KeluarBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PenentuJumlahHari().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BulanCombo;
    private javax.swing.JButton HapusBT;
    private javax.swing.JLabel HasilLabel;
    private javax.swing.JButton HitungBT;
    private javax.swing.JButton KeluarBT;
    private javax.swing.JButton SimpanBT;
    private javax.swing.JTextField TahunTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
